### PR TITLE
Fix TCP connection tracking memory leak

### LINKED ISSUE #766: Panic on udpsession
I got the panic two times this week. How can i handle this?

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x93e4db]

goroutine 129363104 [running]:
github.com/miekg/dns.(*SessionUDP).RemoteAddr(...)
	/build/go/src/github.com/miekg/dns/udp.go:34
github.com/miekg/dns.(*response).RemoteAddr(0xc0025ebdd0, 0xc0001d6a80, 0xc000952d72)
	/build/go/src/github.com/miekg/dns/server.go:773 +0x5b

### LINKED ISSUE #807: Server leaks memory on every TCP connection
Hello,

These insertions into `srv.conns`:

https://github.com/miekg/dns/blob/6ae357d393978566133a91aa1d4207b4f67da2c1/server.go#L496

are never released when the connection is closed:

https://github.com/miekg/dns/blob/6ae357d393978566133a91aa1d4207b4f67da2c1/server.go#L575-L585

The preceding call to `w.Close()` nils out `w.tcp`; the `delete()` has no effect, so the map grows without bound.

I use this library by way of [coredns/coredns](https://github.com/coredns/coredns).  Here is what the leak looks like after a quick local test (y-axis is RSS bytes):

screen shot 2018-11-03 at 04 23 29

I then applied this patch and tried again:

```
diff --git a/server.go b/server.go
index 4b4ec33c..ac655c4e 100644
--- a/server.go
+++ b/server.go
@@ -573,14 +573,14 @@ func (srv *Server) serve(w *response) {
        }

        defer func() {
-               if !w.hijacked {
-                       w.Close()
-               }
-
                srv.lock.Lock()
                delete(srv.conns, w.tcp)
                srv.lock.Unlock()

+               if !w.hijacked {
+                       w.Close()
+               }
+
                w.wg.Done()
        }()

```

Results:

screen shot 2018-11-03 at 04 26 02

### PR DESCRIPTION
**Pull request by tmthrgd**
This refactors how `response.Close` works. This fixes both the memory leak observed in #807 and a similar memory leak that would occur if `Close` was called manually by the handler. The `checkInProgressQueriesAtShutdownServer` test now checks the tracking map is empty after `ShutdownContext` returns.

Along for the ride are some changes to which `response` methods ~panic-after-`Close`~ (edit: fail-after-`Close`), this fixes #766 and allows `LocalAddr` and `RemoteAddr` to work after `Close`.

`Close` also now returns an error if called multiple times.

Fixes #807
Fixes #766
Updates #769

### CODE REVIEW

File: server.go [hunk 1]
```diff
@@ -728,6 +729,10 @@ func (srv *Server) readUDP(conn *net.UDPConn, timeout time.Duration) ([]byte, *S
 
 // WriteMsg implements the ResponseWriter.WriteMsg method.
 func (w *response) WriteMsg(m *Msg) (err error) {
+	if w.closed {
+		panic("dns: WriteMsg called after Close")
```
Comment (miekg) [inline server.go]: not a superfan of all these panics

Comment (miekg) [reply server.go]: better IHMO to just return Err{err: "text"} on these

Comment (tmthrgd) [reply server.go]: Ack.
