### PR TITLE
Prohibit newlines before record data in the ZoneParser

### LINKED ISSUE #901: Zone file parsing ignores meaningful line boundaries
When parsing zone files, a line break immediately following record type is ignored, resulting in acceptance and misinterpretation of invalid input:
```go
$ cat main.go
package main

import (
	"fmt"
	"github.com/miekg/dns"
	"strings"
)

func main() {
	fmt.Printf("; miekg/dns version: %v\n", dns.Version)

	zone := `
$ORIGIN example.com.
example.com. 3600 IN SOA ns.example.net. hostmaster.example.com. 1 86400 60 86400 3600
example.com. 3600 NS ns.example.net.

example.com. 60 PX
1000 TXT 1K
`
	for token := range dns.ParseZone(strings.NewReader(zone), "", "") {
		if token.Error != nil {
			fmt.Printf("; ERROR: %v\n", token.Error)
		} else {
			fmt.Println(token.RR.String())
		}
	}
}

$ go run main.go
; miekg/dns version: 1.1.3
example.com.	3600	IN	SOA	ns.example.net. hostmaster.example.com. 1 86400 60 86400 3600
example.com.	3600	IN	NS	ns.example.net.
example.com.	60	IN	PX	1000 TXT.example.com. 1K.example.com.
```

### PR DESCRIPTION
**Pull request by tmthrgd**
This also includes several simplifications to the parsing code.

Another approach that doesn't need to add the `Peek` method is to pass the first `lex` token directly to the `parse` method like: `parse(c *zlexer, l lex, origin string) *ParseError`. That may be simpler and preferred, but it doesn't otherwise add much.

There is one `TODO` in this PR, previously `slurpRemainder` was only called for some RR types on  dynamic updates. I'm not sure if this is actually observable or not though.

This may still need some polish, but it's here for review at least.

Fixes #901

### CODE REVIEW

File: scan.go [hunk 1]
```diff
@@ -671,6 +689,27 @@ func (zp *ZoneParser) Next() (RR, bool) {
...
+	case TypeANY, TypeNULL, TypeOPT, TypeTSIG:
+		return false
+	default:
+		return true
+	}
+}
+
+func allowDynamicUpdate(rr RR) bool {
+	switch rr.(type) {
+	case *TKEY, *RFC3597, *PrivateRR:
```
Comment (miekg) [inline scan.go]: Think we should only check for PrivateRRs

File: privaterr.go [hunk 2]
```diff
@@ -85,7 +85,7 @@ Fetch:
 
 	err := r.Data.Parse(text)
 	if err != nil {
-		return &ParseError{file, err.Error(), l}
+		return &ParseError{"", err.Error(), l}
```
Comment (miekg) [inline privaterr.go]: think `file` is/was quite useful here (and in the other `parse` functions)

File: dns.go [hunk 3]
```diff
@@ -54,7 +54,7 @@ type RR interface {
 	// parse parses an RR from zone file format.
 	//
 	// This will only be called on a new and empty RR type with only the header populated.
-	parse(c *zlexer, origin, file string) *ParseError
+	parse(c *zlexer, origin string) *ParseError
```
Comment (miekg) [inline dns.go]: I think we can just give this a `*ZoneParser` which holds all the info we need (origin, file and the lexer)

File: privaterr.go (hunk 2 above)
Comment (tmthrgd) [reply privaterr.go]: The file is added back to the error inside `ZoneParser.Next`. I agree that's not entirely clear, but I'm not sure where that could be documented. (`zp.setParseError` uses `zp.file` to fill in the `file` field).

File: scan.go (hunk 1 above)
Comment (tmthrgd) [reply scan.go]: Acknowledged.

File: dns.go (hunk 3 above)
Comment (tmthrgd) [reply dns.go]: We could do that. I'm not sure it really gives us much though.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Prohibit newlines b..." ]
>> @@ -85,7 +85,7 @@ Fetch:
>
> 	err := r.Data.Parse(text)
> 	if err != nil {
>-		return &ParseError{file, err.Error(), l}
>+		return &ParseError{"", err.Error(), l}
>
>The file is added back to the error inside `ZoneParser.Next`. I agree that's not entirely clear, but I'm not sure where that could be documented. (`zp.setParseError` uses `zp.file` to fill in the `file` field).

ok, fair enough. Maybe we can drop that (file) field at some point then?

File: scan.go [hunk 4]
```diff
@@ -671,6 +693,25 @@ func (zp *ZoneParser) Next() (RR, bool) {
...
+	case TypeANY, TypeNULL, TypeOPT, TypeTSIG:
+		return false
+	default:
+		return true
+	}
+}
+
+// allowDynamicUpdate returns true if the record allows for dynamic updates
+// when parsing zone files.
+func allowDynamicUpdate(rr RR) bool {
```
Comment (miekg) [inline scan.go]:
```suggestion
func isPrivateRR(rr RR) bool {
```

File: scan.go [hunk 5]
```diff
@@ -671,6 +693,25 @@ func (zp *ZoneParser) Next() (RR, bool) {
...
+func canParseAsRR(rrtype uint16) bool {
+	switch rrtype {
+	case TypeANY, TypeNULL, TypeOPT, TypeTSIG:
+		return false
+	default:
+		return true
+	}
+}
+
+// allowDynamicUpdate returns true if the record allows for dynamic updates
```
Comment (miekg) [inline scan.go]:
```suggestion
// isPrivateRR  returns true if rr is of type PrivateRR
```

File: scan.go [hunk 6]
```diff
@@ -671,6 +693,25 @@ func (zp *ZoneParser) Next() (RR, bool) {
...
+// when parsing zone files.
```
Comment (miekg) [inline scan.go]:
```suggestion
```

File: scan.go [hunk 7]
```diff
@@ -671,6 +693,25 @@ func (zp *ZoneParser) Next() (RR, bool) {
...
+func allowDynamicUpdate(rr RR) bool {
+	_, isPrivate := rr.(*PrivateRR)
+	return !isPrivate
```
Comment (miekg) [inline scan.go]:
```suggestion
	return isPrivate
```

File: scan.go [hunk 8]
```diff
@@ -650,19 +648,43 @@ func (zp *ZoneParser) Next() (RR, bool) {
...
-					e.lex = l // Uh, dirty
+			var rr RR
+			if newFn, ok := TypeToRR[h.Rrtype]; ok && canParseAsRR(h.Rrtype) {
+				rr = newFn()
+				*rr.Header() = *h
+			} else {
+				rr = &RFC3597{Hdr: *h}
+			}
+
+			if allowDynamicUpdate(rr) && zp.c.Peek().token == "" {
```
Comment (miekg) [inline scan.go]:
```suggestion
			if !isPrivateRR(rr) && zp.c.Peek().token == "" {
```

**Comment by miekg** [comment]
the test can be slightly smaller and it might make sense to test with braces as well as that is valid and should parse:
~~~ go
func TestUnexpectedNewline(t *testing.T) {
	zone := `
example.com. 60 PX
1000 TXT 1K
`
	zp := NewZoneParser(strings.NewReader(zone), "example.com.", "")
	for _, ok := zp.Next(); ok; _, ok = zp.Next() {
	}

	const expect = `dns: unexpected newline: "\n" at line: 2:18`
	if err := zp.Err(); err == nil || err.Error() != expect {
		t.Errorf("expected error to contain %q, got %v", expect, err)
	}

	zone = `
example.com. 60 PX (
1000 TXT 1K )
`
	zp = NewZoneParser(strings.NewReader(zone), "example.com.", "")
	for t, ok := zp.Next(); ok; t, ok = zp.Next() {
	}

	if err := zp.Err(); err != nil {
		t.Errorf("expected an error, got none")
	}
}
~~~

**Comment by miekg** [comment]
some other nits, but lgtm.

**Comment by tmthrgd** [comment]
This fell off my radar, but I addressed the nits.

**Comment by miekg** [comment]
awesome, thank you!

File: scan.go [hunk 9]
```diff
@@ -671,6 +694,18 @@ func (zp *ZoneParser) Next() (RR, bool) {
 	return nil, false
 }
 
+// canParseAsRR returns true if the record type can be parsed as a
+// concrete RR. It blacklists certain record types that must be parsed
+// according to RFC 3597 because they lack a presentation format.
+func canParseAsRR(rrtype uint16) bool {
```
Comment (gibson042) [inline scan.go]: I would invert this and rename it to something like `mustParseAsGeneric`, using vocabulary from [RFC 3597](https://tools.ietf.org/html/rfc3597#section-5).

Comment (tmthrgd) [reply scan.go]: If I touch this again in a future PR, I can certainly consider doing that.
