### PR TITLE
Avoid overriding aLongTimeAgo read deadline

### LINKED ISSUE #756: Travis build hangs
The Travis build has reached `go test` and hung before any tests have run several times now before being terminated by Travis CI.

It's happened recently in:
[job 433357210](https://travis-ci.org/miekg/dns/jobs/433357210)—go 1.10—as part of #754, and
[job 433352922](https://travis-ci.org/miekg/dns/jobs/433352922)—go tip—as part of #751.

This failure is transient and the test will pass after being reset. This should be investigated.

This is an example of log output:
```
travis_time:start:32705ed3
$ go test $TESTS


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

### PR DESCRIPTION
**Pull request by tmthrgd**
The `(*Server).readTCP` and `(*Server).readUDP` methods both call `SetReadDeadline`. If they race with `ShutdownContext`, they can override the `aLongTimeAgo` read deadline that is set in `ShutdownContext`. That will cause `ShutdownContext` to hang or timeout.

~:crossed_fingers: Let's see if this works.~

Updates #756
Updates #763

### CODE REVIEW

**Comment by tmthrgd** [comment]
Damn, didn't fix it. @miekg This is still worth merging anyhow as it is still a race and it should have been in the original PR.

File: server.go [hunk 1]
```diff
@@ -666,7 +666,14 @@ func (srv *Server) serveDNS(w *response) {
 }
 
 func (srv *Server) readTCP(conn net.Conn, timeout time.Duration) ([]byte, error) {
-	conn.SetReadDeadline(time.Now().Add(timeout))
+	if srv.isStarted() {
+		// If we race with ShutdownContext, a distant read
+		// deadline will be set to unblock the read below.
```
Comment (tmthrgd) [inline server.go]: I don’t like the ‘a distant read deadline’ wording, I’ll update it.

**Comment by miekg** [comment]
:/
was just about to say "nice find"! But then I saw your other comments.

/lgtm
