### PR TITLE
Prevent timeout in TestConcurrentExchanges

### LINKED ISSUE #861: TestConcurrentExchanges can cause timeout
This caused a test failure after merging #859.

While `ShutdownContext` appears in the stack trace for `goroutine 41` and it may appear to be related to #756, that's a red herring and it's unrelated. If you comment out the following line, the test failure is reproduced: https://github.com/miekg/dns/blob/ff7d4450818a0cfaaca639e20e0eb4cf7299bd05/client_test.go#L581

The test is designed to cover the `SingleInflight` code, and I think due to goroutine scheduling the request is reaching the server and receiving a response *before* the second request has even been made. This causes two requests to `handler` which causes `waiting` to block indefinitely as it's only drained once.

I'll have to look closer at what the fix is, but until then restart the build because it should be transient.

```
=== RUN   TestConcurrentExchanges
SIGQUIT: quit
PC=0x487893 m=0 sigcode=0
goroutine 7 [syscall]:
runtime.notetsleepg(0xe04820, 0x345b9585b9e, 0x18)
	/home/travis/.gimme/versions/go/src/runtime/lock_futex.go:227 +0x34 fp=0xc000044760 sp=0xc000044730 pc=0x433914
runtime.timerproc(0xe04800)
	/home/travis/.gimme/versions/go/src/runtime/time.go:311 +0x304 fp=0xc0000447d8 sp=0xc000044760 pc=0x475564
runtime.goexit()
	/home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000447e0 sp=0xc0000447d8 pc=0x485581
created by runtime.(*timersBucket).addtimerLocked
	/home/travis/.gimme/versions/go/src/runtime/time.go:169 +0x10e
goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000b4200, 0xa382a3, 0x17, 0xa52ce0, 0x1)
	/home/travis/.gimme/versions/go/src/testing/testing.go:914 +0x6c8
testing.runTests.func1(0xc0000b4200)
	/home/travis/.gimme/versions/go/src/testing/testing.go:1154 +0xa9
testing.tRunner(0xc0000b4200, 0xc000095d48)
	/home/travis/.gimme/versions/go/src/testing/testing.go:862 +0x163
testing.runTests(0xc00000e2e0, 0xdfe780, 0xd0, 0xd0, 0x0)
	/home/travis/.gimme/versions/go/src/testing/testing.go:1152 +0x522
testing.(*M).Run(0xc0001a8000, 0x0)
	/home/travis/.gimme/versions/go/src/testing/testing.go:1069 +0x2ea
main.main()
	_testmain.go:670 +0x333
goroutine 41 [select]:
github.com/miekg/dns.(*Server).ShutdownContext(0xc000267100, 0xad18e0, 0xc00001c180, 0xc000001800, 0xa529f8)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:449 +0x3ef
github.com/miekg/dns.(*Server).Shutdown(0xc000267100, 0x0, 0x0)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:413 +0x7d
github.com/miekg/dns.TestConcurrentExchanges(0xc0000b5300)
	/home/travis/gopath/src/github.com/miekg/dns/client_test.go:592 +0x85e
testing.tRunner(0xc0000b5300, 0xa52ce0)
	/home/travis/.gimme/versions/go/src/testing/testing.go:862 +0x163
created by testing.(*T).Run
	/home/travis/.gimme/versions/go/src/testing/testing.go:913 +0x690
goroutine 60 [chan send]:
github.com/miekg/dns.TestConcurrentExchanges.func1(0xad6640, 0xc0001b3c00, 0xc0001c93b0)
	/home/travis/gopath/src/github.com/miekg/dns/client_test.go:548 +0x8d
github.com/miekg/dns.HandlerFunc.ServeDNS(0xc000276420, 0xad6640, 0xc0001b3c00, 0xc0001c93b0)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:52 +0x6a
github.com/miekg/dns.(*ServeMux).ServeDNS(0xc00000e280, 0xad6640, 0xc0001b3c00, 0xc0001c93b0)
	/home/travis/gopath/src/github.com/miekg/dns/serve_mux.go:128 +0xf6
github.com/miekg/dns.(*Server).serveDNS(0xc000267100, 0xc0001b3c00)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:688 +0x511
github.com/miekg/dns.(*Server).serve(0xc000267100, 0xc0001b3c00)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:573 +0x72a
github.com/miekg/dns.(*Server).worker(0xc000267100, 0xc0001b3b80)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:269 +0x3bf
created by github.com/miekg/dns.(*Server).spawnWorker
	/home/travis/gopath/src/github.com/miekg/dns/server.go:284 +0xf9
goroutine 57 [semacquire]:
sync.runtime_Semacquire(0xc0001cb7c4)
	/home/travis/.gimme/versions/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc0001cb7c4)
	/home/travis/.gimme/versions/go/src/sync/waitgroup.go:130 +0xb0
github.com/miekg/dns.(*Server).serveUDP.func1(0xc0001cb7c4, 0xc000267100)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:528 +0x51
github.com/miekg/dns.(*Server).serveUDP(0xc000267100, 0xc0001d60b8, 0x0, 0x0)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:538 +0x3eb
github.com/miekg/dns.(*Server).ActivateAndServe(0xc000267100, 0x0, 0x0)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:399 +0x4f0
github.com/miekg/dns.RunLocalUDPServerWithFinChan.func1(0xc000248ba0, 0xc000267100, 0xad5800, 0xc0001d60b8)
	/home/travis/gopath/src/github.com/miekg/dns/server_test.go:84 +0x39
created by github.com/miekg/dns.RunLocalUDPServerWithFinChan
	/home/travis/gopath/src/github.com/miekg/dns/server_test.go:83 +0x354
goroutine 42 [IO wait]:
internal/poll.runtime_pollWait(0x7fac2c8ebdc0, 0x72, 0xc0001ec848)
	/home/travis/.gimme/versions/go/src/runtime/netpoll.go:182 +0x55
internal/poll.(*pollDesc).wait(0xc0001a8f18, 0x72, 0x200, 0x200, 0xc00001a900)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:87 +0xe4
internal/poll.(*pollDesc).waitRead(...)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).ReadMsg(0xc0001a8f00, 0xc00025da00, 0x200, 0x200, 0xc00001a900, 0x28, 0x28, 0x0, 0x0, 0x0, ...)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_unix.go:243 +0x29d
net.(*netFD).readMsg(0xc0001a8f00, 0xc00025da00, 0x200, 0x200, 0xc00001a900, 0x28, 0x28, 0x19, 0x28, 0x8, ...)
	/home/travis/.gimme/versions/go/src/net/fd_unix.go:214 +0xa1
net.(*UDPConn).readMsg(0xc000010118, 0xc00025da00, 0x200, 0x200, 0xc00001a900, 0x28, 0x28, 0x4274a0, 0x0, 0xc00001a900, ...)
	/home/travis/.gimme/versions/go/src/net/udpsock_posix.go:59 +0xb5
net.(*UDPConn).ReadMsgUDP(0xc000010118, 0xc00025da00, 0x200, 0x200, 0xc00001a900, 0x28, 0x28, 0x94dd55, 0xc00025da00, 0x200, ...)
	/home/travis/.gimme/versions/go/src/net/udpsock.go:142 +0xbc
github.com/miekg/dns.ReadFromSessionUDP(0xc000010118, 0xc00025da00, 0x200, 0x200, 0x0, 0x0, 0xe01060, 0x881417)
	/home/travis/gopath/src/github.com/miekg/dns/udp.go:42 +0x149
github.com/miekg/dns.(*Server).readUDP(0xc0000b5400, 0xc000010118, 0x34630b8a000, 0x48fa5d, 0xc0000b54cc, 0xc0ffffffff, 0xc000000000, 0xc0000b54c4, 0xc0001ecdf0)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:744 +0x156
github.com/miekg/dns.(*defaultReader).ReadUDP(0xc000010130, 0xc000010118, 0x34630b8a000, 0xc00025d800, 0x19, 0x200, 0xc000270460, 0x0, 0x0)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:170 +0x8e
github.com/miekg/dns.(*Server).serveUDP(0xc0000b5400, 0xc000010118, 0x0, 0x0)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:535 +0x291
github.com/miekg/dns.(*Server).ActivateAndServe(0xc0000b5400, 0x0, 0x0)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:399 +0x4f0
github.com/miekg/dns.RunLocalUDPServerWithFinChan.func1(0xc000211980, 0xc0000b5400, 0xad5800, 0xc000010118)
	/home/travis/gopath/src/github.com/miekg/dns/server_test.go:84 +0x39
created by github.com/miekg/dns.RunLocalUDPServerWithFinChan
	/home/travis/gopath/src/github.com/miekg/dns/server_test.go:83 +0x354
rax    0xfffffffffffffffc
rbx    0x3b70199e
rcx    0x487893
rdx    0x0
rdi    0xe04820
rsi    0x80
rbp    0xc0000446e8
rsp    0xc0000446a0
r8     0x0
r9     0x0
r10    0xc0000446d8
r11    0x202
r12    0x7d584999066
r13    0x1
r14    0xc0001e4900
r15    0xc0001a8f18
rip    0x487893
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
exit status 2
FAIL	github.com/miekg/dns	600.007s
```

### PR DESCRIPTION
**Pull request by tmthrgd**
This eliminates the possibility of deadlocking the handler and also simplifies the test considerably.

Fixes #861

### CODE REVIEW

File: singleinflight.go [hunk 1]
```diff
@@ -49,9 +51,11 @@ func (g *singleflight) Do(key string, fn func() (*Msg, time.Duration, error)) (v
 	c.val, c.rtt, c.err = fn()
 	c.wg.Done()
 
-	g.Lock()
-	delete(g.m, key)
-	g.Unlock()
+	if !g.dontDeleteForTesting {
```
Comment (miekg) [inline singleinflight.go]: this is maybe a bit of a nit, but can we do this without changing the non-test code? Wrap this in a new struct for testing and override this function?

Comment (tmthrgd) [reply singleinflight.go]: I didn’t love that either. I’m not sure I see how though. This seems like the most minimal change to me, but I’m open to any suggestions.

Comment (tmthrgd) [reply singleinflight.go]: I didn’t love that either. I’m not sure I see how though. This seems like the most minimal change to me, but I’m open to any suggestions.
